---
roles:
  - name: kameshsampath.minikube
    src: https://github.com/kameshsampath/ansible-role-minikube
    version: main
collections:
  - name: kameshsampath.gloo
    src: https://github.com/kameshsampath/kameshsampath.gloo
    version: main
