- name: "Install Istio"
  include_tasks: install.yml
  vars:
    gloo_agent_cluster: "{{ gloo_cluster_item.value }}"
    gloo_agent_cluster_name: "{{ gloo_cluster_item.value.cluster_name | default( gloo_cluster_item.key )  }}"
    mgmt_k8s_context: "{{ gloo_clusters.mgmt.k8s_context  }}"
  loop: "{{ gloo_clusters | dict2items }}"
  loop_control:
    label: "{{ gloo_cluster_item.key }}"
    loop_var: gloo_cluster_item
  register: gloo_cluster_mgmt_nodes
  when: gloo_cluster_item.value.install_istio | default(false)

- name: "Rollback Istio"
  include_tasks: rollback.yml
  vars:
    gloo_agent_cluster: "{{ gloo_cluster_item.value }}"
    gloo_agent_cluster_name: "{{ gloo_cluster_item.value.cluster_name | default( gloo_cluster_item.key )  }}"
    mgmt_k8s_context: "{{ gloo_clusters.mgmt.k8s_context  }}"
  loop: "{{ gloo_clusters | dict2items }}"
  loop_control:
    label: "{{ gloo_cluster_item.key }}"
    loop_var: gloo_cluster_item
  register: gloo_cluster_mgmt_nodes
  when: not ( gloo_cluster_item.value.install_istio | default(true) )