istio_install_namespace: istio-system
istio_gateways_namespace: istio-system
istio_version: 1.11.4
istio_network_name: mymeshnetwork
istio_trust_domain: "{{ mesh_cluster_domain | default('cluster.local') }}"
istio_trust_domain_aliases: []
istio_revision_regex: '(?P<major>^\d{1,3})\.(?P<minor>\d{1,3})\.(?P<patch>\d{1,3})(?P<rc>\-*\w*\.*\d*)$'
# TODO - ability to add the operator specs from local file system
istio_operator_specs: []
gloo_mesh_iops_query: 'resources[?spec.revision == `{{ istio_revision }}`].{name: metadata.name, namespace: metadata.namespace }'