- hosts: all

  vars:
    work_dir: "{{ playbook_dir }}/work"
    minikube_profiles:
      mgmt:
        create: no
        destroy: yes
      cluster1:
        create: no
        destroy: yes
      cluster2:
        create: no
        destroy: yes
  roles:
    - role: kameshsampath.minikube
