- hosts: all

  vars_files:
    - vars.yml
  vars:
    work_dir: "{{ playbook_dir }}"

  roles:
    - role: kameshsampath.gloo

  tasks:
    - name: "Merge Kubconfig"
      set_fact: 
        kubeconfig: "{{ lookup('fileglob', work_dir +'/.kube/*.kubeconfig') | regex_replace(',',':') }}"

    - name: "Debug::Available Kubeconfigs"
      debug:
        var: kubeconfig
    
    - name: "Merge and Flatten Kubeconfig"
      local_action:
        module: ansible.builtin.command
        argv:
         - kubectl 
         - config
         - view 
         - --flatten
      register: merged_kubeconfig
      environment:
         KUBECONFIG: "{{ kubeconfig  }}"


    - name: "Save work Kubeconfig"
      local_action:
        module: ansible.builtin.copy
        dest: "{{ work_dir }}/.kube/config"
        content: "{{ merged_kubeconfig.stdout | from_yaml | to_nice_yaml(indent=2) }}"

    - name: "Save Work .envrc"
      local_action:
        module: ansible.builtin.template
        dest: "{{ playbook_dir }}/.envrc"
        src: "{{ playbook_dir }}/templates/.envrc.j2"
    
