portal_enable: yes
enable_edge_federation: no
gloo_home_dir: "{{ work_dir | default( ansible_env.HOME + '/.gloo' ) }}"
releaseQuery: '[*].tag_name'
gloo_install_override_files: []
gloo_portal_override_files: []